import routes.AppRouter;
import spark.Spark;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FcmMiddlewareApp {

    public static void main(String... args) {

        System.out.println("Start FcmMiddlewareApp");
        Spark.port(8080);
        var router = new AppRouter();
        router.initAppRoutes();
        router.register();

        //Just to stop server
        Spark.get("stop", ((request, response) -> {
            Spark.stop();
            return "";
        }));
    }
}
